import { IncidentStatus, IncidentType, Prisma } from '@prisma/client';
import { db } from '@/lib/db';
import { statusLabel, typeLabel } from '@/lib/labels';
export type AnalyticsFilters={period:'today'|'7d'|'30d'|'custom';start?:string;end?:string;type?:IncidentType;status?:IncidentStatus;cameraId?:string};
const types=new Set(Object.keys(typeLabel)),statuses=new Set(Object.keys(statusLabel));
export function parseAnalyticsFilters(q:Record<string,string|undefined>):AnalyticsFilters{const period=q.period==='today'||q.period==='7d'||q.period==='custom'?q.period:'30d';return{period,start:/^\d{4}-\d{2}-\d{2}$/.test(q.start??'')?q.start:undefined,end:/^\d{4}-\d{2}-\d{2}$/.test(q.end??'')?q.end:undefined,type:types.has(q.type??'')?q.type as IncidentType:undefined,status:statuses.has(q.status??'')?q.status as IncidentStatus:undefined,cameraId:/^[0-9a-f-]{36}$/.test(q.cameraId??'')?q.cameraId:undefined};}
export function analyticsWhere(f:AnalyticsFilters):Prisma.IncidentWhereInput{const now=new Date();let start:Date;if(f.period==='today'){start=new Date(now);start.setHours(0,0,0,0);}else if(f.period==='7d')start=new Date(now.getTime()-6*86400000);else if(f.period==='custom'&&f.start)start=new Date(`${f.start}T00:00:00.000Z`);else start=new Date(now.getTime()-29*86400000);const end=f.period==='custom'&&f.end?new Date(`${f.end}T00:00:00.000Z`):new Date(now.getTime()+1);const where:Prisma.IncidentWhereInput={createdAt:{gte:start,lt:end}};if(f.type)where.type=f.type;if(f.status)where.status=f.status;if(f.cameraId)where.cameraId=f.cameraId;return where;}
const count=(v:string[])=>Object.entries(v.reduce<Record<string,number>>((a,x)=>({...a,[x]:(a[x]??0)+1}),{}));
export async function getAnalytics(filters:AnalyticsFilters){const where=analyticsWhere(filters);const[incidents,cameras]=await Promise.all([db.incident.findMany({where,include:{camera:true,history:{where:{newStatus:'RESOLVED'},select:{createdAt:true},orderBy:{createdAt:'asc'},take:1}},orderBy:{createdAt:'desc'},take:1000}),db.camera.findMany({orderBy:{name:'asc'},select:{id:true,name:true}})]);const response=incidents.filter(i=>i.claimedAt).map(i=>i.claimedAt!.getTime()-i.createdAt.getTime()),close=incidents.flatMap(i=>i.history[0]?[i.history[0].createdAt.getTime()-i.createdAt.getTime()]:[]);return{filters,incidents,cameras,byDay:count(incidents.map(i=>i.createdAt.toISOString().slice(0,10))).sort(([a],[b])=>a.localeCompare(b)),byType:count(incidents.map(i=>i.type)),byStatus:count(incidents.map(i=>i.status)),byCamera:count(incidents.map(i=>i.camera?.name??'Без камеры')),kpi:{total:incidents.length,active:incidents.filter(i=>!['RESOLVED','REJECTED'].includes(i.status)).length,closed:incidents.filter(i=>i.status==='RESOLVED').length,critical:incidents.filter(i=>i.severity==='CRITICAL').length,falls:incidents.filter(i=>i.type==='PERSON_FALL').length,avgResponseMs:response.length?Math.round(response.reduce((a,b)=>a+b,0)/response.length):null,avgCloseMs:close.length?Math.round(close.reduce((a,b)=>a+b,0)/close.length):null}};}
export const duration=(ms:number|null)=>ms==null?'—':`${Math.round(ms/60000)} мин`;
