import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {db} from '../src/lib/db';
import {claimIncident,decideIncident,assignIncident,advanceTask} from '../src/lib/workflow';
import {dispatchCritical} from '../src/lib/dispatch';

test('transactional lifecycle, conflict protection, photo requirement and reopen',async()=>{
  assert.match(process.env.DATABASE_URL||'',/aqtau_test/,'Use isolated aqtau_test database');
  const tag=randomUUID();
  const op1=await db.user.create({data:{name:'Test op1',email:tag+'o1@test.local',passwordHash:'unused',role:'OPERATOR'}});
  const op2=await db.user.create({data:{name:'Test op2',email:tag+'o2@test.local',passwordHash:'unused',role:'OPERATOR'}});
  const worker=await db.user.create({data:{name:'Test worker',email:tag+'w@test.local',passwordHash:'unused',role:'WORKER',workerProfile:{create:{specialization:'WATER'}}}});
  const resident=await db.user.create({data:{name:'Test resident',email:tag+'r@test.local',passwordHash:'unused',role:'RESIDENT'}});
  const i=await db.incident.create({data:{title:'Test lifecycle',type:'WATER_LEAK',source:'RESIDENT',severity:'MEDIUM',lat:43.65,lng:51.17,address:'Актау',reporterId:resident.id}});
  const claims=await Promise.allSettled([claimIncident(i.id,op1.id),claimIncident(i.id,op2.id)]);
  assert.equal(claims.filter(r=>r.status==='fulfilled').length,1,'only one operator wins');
  const claimed=await db.incident.findUniqueOrThrow({where:{id:i.id}});
  const winner=claimed.assignedOperatorId!;
  await decideIncident(i.id,winner,'CONFIRMED');
  await assignIncident(i.id,winner,worker.id,null);
  for(const next of ['ACCEPTED','ON_THE_WAY','ON_SITE'] as const) await advanceTask(i.id,worker.id,next,'');
  await assert.rejects(advanceTask(i.id,worker.id,'COMPLETED','Done'),/фото/);
  const attempts=await Promise.allSettled([advanceTask(i.id,worker.id,'COMPLETED','Done','/test-after.png'),advanceTask(i.id,worker.id,'COMPLETED','Done','/duplicate.png')]);
  assert.equal(attempts.filter(r=>r.status==='fulfilled').length,1);
  assert.equal(await db.incidentMedia.count({where:{incidentId:i.id,stage:'AFTER'}}),1);
  assert.equal((await db.incident.findUniqueOrThrow({where:{id:i.id}})).status,'RESOLVED');
  assert.ok(await db.notification.count({where:{userId:resident.id}})>0);
  await decideIncident(i.id,winner,'REOPENED','Needs additional work');
  assert.equal(await db.workerViolation.count({where:{incidentId:i.id}}),1);
  assert.equal((await db.workerTask.findUniqueOrThrow({where:{incidentId:i.id}})).status,'ASSIGNED');
  const critical=await db.incident.create({data:{title:'Test critical transfer',type:'PERSON_FALL',source:'CAMERA',severity:'CRITICAL',lat:43.65,lng:51.17,address:'Актау'}});
  await dispatchCritical();
  const first=await db.incident.findUniqueOrThrow({where:{id:critical.id}});
  assert.ok(first.assignedOperatorId);
  await db.incident.update({where:{id:critical.id},data:{claimExpiresAt:new Date(Date.now()-1000)}});
  await dispatchCritical();
  const second=await db.incident.findUniqueOrThrow({where:{id:critical.id}});
  assert.notEqual(first.assignedOperatorId,second.assignedOperatorId);
  await assert.rejects(claimIncident(critical.id,first.assignedOperatorId!),/другой оператор/);
  await db.$disconnect();
});
