import {redirect} from 'next/navigation';
import {ArrowRight,ShieldCheck} from 'lucide-react';
import {currentUser} from '@/lib/auth';
import {demoAccounts,demoEnabled} from '@/lib/demo';
import {loginAction,quickLoginAction} from '../actions';
import SubmitButton from '@/components/submit-button';
import CityIllustration from '@/components/city-illustration';
export default async function Login({searchParams}:{searchParams:Promise<{error?:string}>}){
 const user=await currentUser();if(user)redirect('/'+user.role.toLowerCase());const {error}=await searchParams;
 const roles={OPERATOR:'Диспетчеры',ADMIN:'Администратор',RESIDENT:'Жители',WORKER:'Городские службы'};
 return <div className="login-page"><div className="login-art"><div className="login-brand"><span className="brand-mark"><ShieldCheck/></span> SU AQTAU <small>SAFE CITY SYSTEM</small></div><div className="login-story"><span className="login-kicker">ТЕХНОЛОГИИ НА СТОРОНЕ ГОРОДА</span><h1>Город под контролем.<br/><em>Помощь рядом.</em></h1><p>Единая диспетчерская Актау. От обращения жителя до подтверждённого результата.</p></div><CityIllustration/><div className="login-art-footer"><span>01 / Единая городская среда</span><span>ДЕМОНСТРАЦИОННЫЙ MVP</span></div></div><div className="login-form-side"><div className="login-box"><p className="eyebrow">ДОБРО ПОЖАЛОВАТЬ</p><h2>Ваш город.<br/>Ваше рабочее место.</h2><p className="subtle">Выберите роль, чтобы начать работу с платформой.</p>{error&&<p className="error-banner">{error==='demo'?'Загрузите демо-аккаунты командой db:seed':'Неверный email или пароль'}</p>}{demoEnabled()&&<section className="demo-fast-login"><p>Демонстрационные аккаунты · вход без пароля</p>{Object.entries(roles).map(([role,label],index)=><details key={role} open={role==='OPERATOR'} className="demo-role-group"><summary><span className="role-index">0{index+1}</span>{label}</summary><form action={quickLoginAction} className="quick-login-form">{demoAccounts.filter(a=>a.role===role).map(a=><button name="email" value={a.email} className="quick-login-button" key={a.email}><span><b>{a.name}</b><small>{a.email}</small></span><ArrowRight size={18} className="ml-auto"/></button>)}</form></details>)}</section>}<details className="password-entry"><summary className="subtle cursor-pointer">Войти по email и паролю</summary><form action={loginAction}><label className="field">Email<input name="email" type="email" required autoComplete="username"/></label><label className="field">Пароль<input name="password" type="password" required autoComplete="current-password"/></label><SubmitButton>Войти <ArrowRight size={16}/></SubmitButton></form></details><div className="login-security"><ShieldCheck size={16}/> Единое пространство жителей и городских служб</div></div></div></div>;
}
