'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useEffect, useState } from 'react';
import { Bell, LayoutDashboard, ListChecks, MapPinned, Menu, Settings, ShieldCheck, UserRound, X } from 'lucide-react';
import { logoutAction } from '@/app/actions';

type SimpleUser = { name: string; email: string; role: 'RESIDENT' | 'WORKER' | 'OPERATOR' };
const text = { ru: { overview:'Обзор', incidents:'События', tasks:'Мои задачи', reports:'Мои обращения', settings:'Настройки', logout:'Выйти', role_OPERATOR:'Оператор', role_WORKER:'Работник', role_RESIDENT:'Житель', city:'Городская платформа безопасности' }, kk: { overview:'Шолу', incidents:'Оқиғалар', tasks:'Менің тапсырмаларым', reports:'Өтініштерім', settings:'Баптаулар', logout:'Шығу', role_OPERATOR:'Оператор', role_WORKER:'Қызметкер', role_RESIDENT:'Тұрғын', city:'Қалалық қауіпсіздік платформасы' } };
export default function Shell({ user, children, notifications = 0 }: { user: SimpleUser; children: React.ReactNode; notifications?: number }) {
  const path = usePathname(); const [open,setOpen] = useState(false); const [dark,setDark] = useState(false); const [lang,setLang] = useState<'ru'|'kk'>('ru');
  useEffect(() => { const theme = localStorage.getItem('theme') === 'dark'; setDark(theme); document.documentElement.classList.toggle('dark', theme); setLang(localStorage.getItem('lang') === 'kk' ? 'kk' : 'ru'); }, []);
  useEffect(() => { document.documentElement.classList.toggle('dark',dark); localStorage.setItem('theme',dark ? 'dark' : 'light'); }, [dark]);
  useEffect(() => { localStorage.setItem('lang',lang); }, [lang]);
  const t = text[lang]; const main = `/${user.role.toLowerCase()}`;
  const nav = user.role === 'OPERATOR' ? [{ href: main, label: t.overview, icon: LayoutDashboard }, { href: '/operator/incidents', label: t.incidents, icon: MapPinned }] : user.role === 'WORKER' ? [{ href: main, label: t.tasks, icon: ListChecks }] : [{ href: main, label: t.overview, icon: LayoutDashboard }, { href: '/resident/reports', label: t.reports, icon: MapPinned }];
  nav.push({ href: '/settings', label: t.settings, icon: Settings });
  return <div className="app-shell"><aside className={`sidebar ${open ? 'sidebar-open' : ''}`}><div className="brand"><span className="brand-mark"><ShieldCheck size={24}/></span><div><strong>SU AQTAU</strong><small>SAFE CITY SYSTEM</small></div><button className="mobile-only icon-button ml-auto" onClick={() => setOpen(false)} aria-label="Закрыть меню"><X size={20}/></button></div><div className="city-tag"><span className="live-dot"/> АКТАУ · ГОРОДСКАЯ СИСТЕМА</div><nav>{nav.map(item => <Link key={item.href} href={item.href} onClick={() => setOpen(false)} className={`nav-item ${path === item.href ? 'active' : ''}`}><item.icon size={19}/>{item.label}</Link>)}</nav><div className="sidebar-bottom"><div className="support-card"><span>● &nbsp; Система активна</span><p>Демонстрационный режим</p></div><form action={logoutAction}><button className="nav-item w-full" type="submit"><UserRound size={19}/>{t.logout}</button></form></div></aside><div className="main-column"><header className="topbar"><button className="mobile-only icon-button" onClick={() => setOpen(true)} aria-label="Открыть меню"><Menu size={22}/></button><div className="topbar-title"><strong>{t.city}</strong><span>Мониторинг городской среды в реальном времени</span></div><div className="top-actions"><button className="icon-button relative" title={`${notifications} уведомлений`}><Bell size={19}/>{notifications > 0 && <i className="notify-dot"/>}</button><button className="icon-button" title="Тема" onClick={() => setDark(!dark)}>{dark ? '☀' : '☾'}</button><button className="lang-button" onClick={() => setLang(lang === 'ru' ? 'kk' : 'ru')}>{lang.toUpperCase()}</button><div className="profile-chip"><span>{user.name.slice(0,1)}</span><div><b>{user.name}</b><small>{t[`role_${user.role}`]}</small></div></div></div></header><main className="page-content">{children}</main><nav className="mobile-nav">{nav.map(item => <Link key={item.href} href={item.href} className={path === item.href ? 'active' : ''}><item.icon size={19}/><span>{item.label}</span></Link>)}</nav></div></div>;
}
