import Link from 'next/link';
import {requireUser} from '@/lib/auth';
import {db} from '@/lib/db';
import {taskLabel} from '@/lib/labels';
import {SeverityBadge} from '@/components/badges';
import {TypeGlyph} from '@/components/icons';
export default async function Worker(){
 const u=await requireUser('WORKER');const tasks=await db.workerTask.findMany({where:{workerId:u.id},include:{incident:true,route:true},orderBy:[{position:'asc'},{assignedAt:'asc'}]});const active=tasks.filter(t=>t.status!=='COMPLETED');
 return <><div className="page-heading"><div><p className="eyebrow">РАБОЧИЙ ПЛАН</p><h1>Сегодня, {u.name.split(' ')[0]}</h1><p className="subtle">Порядок назначен диспетчером. Время выполнения — плановая оценка.</p></div><span className="badge status-assigned">{active.length} активных задач</span></div><div className="content-grid"><section className="panel"><div className="panel-header"><h2>Последовательность работы</h2></div><div className="panel-body timeline">{active.map((t,n)=><article className="timeline-item" key={t.id}><p className="eyebrow">{n===0?'СЛЕДУЮЩАЯ ЗАДАЧА':'ЗАДАЧА '+(n+1)}</p><strong>{t.plannedStart?.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})||'По назначению'} — {t.plannedEnd?.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})||'уточняется'}</strong><h2 className="text-lg font-bold my-2 flex items-center gap-2"><span className="incident-icon"><TypeGlyph type={t.incident.type} size={17} animate/></span>{t.incident.title}</h2><p>{t.incident.address}</p><SeverityBadge severity={t.incident.severity}/><p>{taskLabel[t.status]}</p><p>{t.route?Math.ceil(t.route.durationSeconds/60)+' мин · '+(t.route.distanceMeters/1000).toFixed(1)+' км от сохранённой позиции':'Переезд: резерв 15 мин, уточните дорожный маршрут'}</p><div className="actions-row"><Link className="button" href={'/incidents/'+t.incidentId}>Открыть задачу</Link><Link className="button secondary" href={'/worker/route/'+t.incidentId}>Маршрут</Link></div></article>)}{!active.length&&<div className="empty-state">Новых назначений пока нет</div>}</div></section><section className="panel"><div className="panel-header"><h2>Выполнено</h2></div><div className="incident-list">{tasks.filter(t=>t.status==='COMPLETED').map(t=><Link className="incident-card" key={t.id} href={'/incidents/'+t.incidentId}><strong>{t.incident.title}</strong><p>{t.completedAt?.toLocaleString('ru-RU')}</p></Link>)}</div></section></div></>;
}

