import Link from 'next/link';
import { ArrowRight, MapPin } from 'lucide-react';
import { requireUser } from '@/lib/auth';
import { db } from '@/lib/db';
import { taskLabel } from '@/lib/labels';
import { TypeGlyph } from '@/components/icons';
import { SeverityBadge } from '@/components/badges';
export const dynamic = 'force-dynamic';
export default async function Worker() { const user = await requireUser('WORKER'); const tasks = await db.workerTask.findMany({ where:{workerId:user.id}, include:{incident:true},orderBy:{assignedAt:'desc'} }); const active = tasks.find(t=>t.status!=='COMPLETED'); return <><div className="page-heading"><div><p className="eyebrow">РАБОЧЕЕ МЕСТО</p><h1>Добрый день, {user.name.split(' ')[0]}</h1><p className="subtle">Ваши задачи и маршрут на сегодня</p></div></div><div className="kpi-grid"><div className="kpi"><span>Всего задач</span><strong>{tasks.length}</strong><small>Назначены вам</small></div><div className="kpi"><span>В работе</span><strong>{tasks.filter(t=>t.status!=='COMPLETED').length}</strong><small>Активные</small></div><div className="kpi"><span>Завершены</span><strong>{tasks.filter(t=>t.status==='COMPLETED').length}</strong><small>Результат сохранён</small></div></div><div className="content-grid"><section className="panel"><div className="panel-header"><h2>Текущая задача</h2></div>{active?<div className="panel-body"><div className="flex items-center gap-3 mb-4"><span className="incident-icon"><TypeGlyph type={active.incident.type} size={18} animate/></span><div><h2 className="font-extrabold text-lg">{active.incident.title}</h2><span className="subtle">{taskLabel[active.status]}</span></div></div><SeverityBadge severity={active.incident.severity}/><p className="mt-4 text-sm">{active.incident.description}</p><p className="subtle flex items-center gap-2 mt-4"><MapPin size={15}/>{active.incident.address}</p><div className="actions-row"><Link href={`/incidents/${active.incidentId}`} className="button">Открыть задачу <ArrowRight size={15}/></Link><Link href={`/worker/route/${active.incidentId}`} className="button secondary">Маршрут</Link></div></div>:<div className="empty-state"><strong>Активных задач нет</strong>Новые назначения появятся здесь</div>}</section><section className="panel"><div className="panel-header"><h2>Все задачи</h2><span>{tasks.length}</span></div><div className="incident-list">{tasks.map(t=><Link key={t.id} href={`/incidents/${t.incidentId}`} className="incident-card block"><div className="flex justify-between gap-2"><strong>{t.incident.title}</strong><span className="badge status-assigned">{taskLabel[t.status]}</span></div><p className="subtle">{t.incident.address}</p></Link>)}{tasks.length===0&&<div className="empty-state">Задач пока нет</div>}</div></section></div></>; }
