import {z} from 'zod';
import Image from 'next/image';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {addCommentAction,assignWorkerAction,claimIncidentAction,updateIncidentAction,updateTaskAction} from '@/app/actions';
import MapView from '@/components/map-view';
import SubmitButton from '@/components/submit-button';
import {SeverityBadge,StatusBadge} from '@/components/badges';
import {requireUser} from '@/lib/auth';
import {db} from '@/lib/db';
import {sourceLabel,taskLabel,typeLabel,statusLabel} from '@/lib/labels';
import {recommendations} from '@/lib/dispatch';
import {TypeGlyph} from '@/components/icons';
import {Star} from 'lucide-react';
export const dynamic='force-dynamic';
export default async function Detail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{toast?:string;error?:string}>}){
 const u=await requireUser(),{id}=await params,{toast,error}=await searchParams;if(!z.string().uuid().safeParse(id).success)notFound();
 const i=await db.incident.findFirst({where:{id,...(u.role==='RESIDENT'?{reporterId:u.id}:u.role==='WORKER'?{assignedWorkerId:u.id}:{})},include:{media:{orderBy:{createdAt:'asc'}},history:{where:u.role==='RESIDENT'?{isPublic:true}:undefined,orderBy:{createdAt:'desc'},include:{actor:{select:{name:true}}}},task:true,assignedWorker:{select:{name:true}},assignedOperator:{select:{name:true}},camera:true}});
  if(!i)notFound();
  const meta=(i.metadata??{}) as Record<string,unknown>;
  const isCvFall=i.type==='PERSON_FALL'&&i.source==='CAMERA';
  const isCvFight=i.type==='FIGHT'&&i.source==='CAMERA';
  const resident=u.role==='RESIDENT',operator=u.role==='OPERATOR',locked=!!i.assignedOperatorId&&i.assignedOperatorId!==u.id;
 const candidates=operator&&!locked&&['CONFIRMED','REOPENED'].includes(i.status)?await recommendations(i):[];
 const nextTask=i.task?.status==='ASSIGNED'?'ACCEPTED':i.task?.status==='ACCEPTED'?'ON_THE_WAY':i.task?.status==='ON_THE_WAY'?'ON_SITE':i.task?.status==='ON_SITE'?'COMPLETED':null;
 const before=i.media.filter(m=>m.stage==='BEFORE'),after=i.media.filter(m=>m.stage==='AFTER');
 return <>{toast&&<div className="toast" role="status">Изменения сохранены</div>}{error&&<div className="error-banner" role="alert">{error}</div>}<div className="page-heading"><div><p className="eyebrow">{resident?'ОБРАЩЕНИЕ':'СОБЫТИЕ'} · № {id.slice(0,8)}</p><h1>{i.title}</h1><p className="subtle">{i.address} · {i.createdAt.toLocaleString('ru-RU')}</p></div><StatusBadge status={i.status}/></div>
 <div className="content-grid"><div className="space-y-4"><section className="panel panel-body"><div className="flex gap-2 mb-3">{!resident&&<SeverityBadge severity={i.severity}/>}<span className="badge status-new"><TypeGlyph type={i.type} size={13} animate/>{typeLabel[i.type]}</span>{!resident&&i.isDemo&&<span className="badge">DEMO / MOCK</span>}</div><p>{i.description}</p>{!resident&&<div className="detail-facts mt-4"><div><span>Источник</span>{sourceLabel[i.source]}</div><div><span>{isCvFall?'Heuristic fall score':isCvFight?'Heuristic fight score':'Confidence'}</span>{i.confidence===null?'—':i.confidence+'%'}</div>{isCvFall&&meta.poseVisibility!=null&&<div><span>Pose visibility</span>{String(meta.poseVisibility)+'%'}</div>}{isCvFight&&meta.peopleCount!=null&&<div><span>People count</span>{String(meta.peopleCount)}</div>}<div><span>Исполнитель</span>{i.assignedWorker?.name||'Не назначен'}</div><div><span>Оператор</span>{i.assignedOperator?.name||'Ожидает принятия'}</div>{i.claimExpiresAt&&!i.claimedAt&&<div><span>Принять до</span>{i.claimExpiresAt.toLocaleTimeString('ru-RU')}</div>}</div>}{!resident&&i.cameraId&&<Link href={'/operator/cameras?camera='+i.cameraId} className="button secondary mt-3">Открыть камеру</Link>}</section>
 <section className="panel"><div className="panel-header"><h2>Фото до / после</h2></div><div className="before-after panel-body">{[['До',before],['После',after]].map(([title,media])=><div key={title as string}><p className="eyebrow">{title as string}</p>{(media as typeof before).length?(media as typeof before).map(m=><Image key={m.id} src={m.url} alt={'Фото '+title} width={700} height={400} unoptimized className="media-preview"/>):<div className="empty-photo">{title==='После'?'Результат ещё не загружен':'Фото источника отсутствует'}</div>}</div>)}</div>{!resident&&i.task?.completionComment&&<div className="panel-body"><strong>{i.assignedWorker?.name}</strong><p>{i.task.completionComment}</p><p className="subtle">Начало: {i.task.startedAt?.toLocaleString('ru-RU')||'—'} · Завершение: {i.task.completedAt?.toLocaleString('ru-RU')||'—'}{i.task.startedAt&&i.task.completedAt&&' · '+Math.max(1,Math.round((i.task.completedAt.getTime()-i.task.startedAt.getTime())/60000))+' мин'}</p></div>}</section>
 <section className="panel"><div className="panel-header"><h2>История {resident?'обращения':'события'}</h2></div><div className="panel-body timeline">{i.history.map(h=><div className="timeline-item" key={h.id}><strong>{resident&&h.newStatus?statusLabel[h.newStatus]:h.action}</strong><time>{h.createdAt.toLocaleString('ru-RU')}{!resident&&' · '+(h.actor?.name||'Система')}</time>{!resident&&h.comment&&<p>{h.comment}</p>}</div>)}</div>{!resident&&<form action={addCommentAction} className="panel-body grid gap-3"><input type="hidden" name="id" value={id}/><label className="field">Внутренний комментарий<textarea name="comment" required maxLength={1000}/></label><SubmitButton>Добавить комментарий</SubmitButton></form>}</section></div>
 <div className="space-y-4"><section className="panel"><div className="panel-header"><h2>{resident?'Ход решения':'Действия'}</h2></div><div className="panel-body space-y-3">{resident&&<p>Мы сообщим об изменении статуса в уведомлениях.</p>}
 {operator&&locked&&<div className="warning-banner">Обрабатывает {i.assignedOperator?.name}. Конфликтующие действия недоступны.</div>}
 {operator&&!locked&&<>{!i.claimedAt&&!['RESOLVED','REJECTED'].includes(i.status)&&<form action={claimIncidentAction}><input type="hidden" name="id" value={id}/><SubmitButton>Принять в обработку</SubmitButton></form>}{['NEW','WAITING_OPERATOR','REOPENED'].includes(i.status)&&<div className="actions-row">{(['CONFIRMED','REJECTED'] as const).map(status=><form action={updateIncidentAction} key={status}><input type="hidden" name="id" value={id}/><input type="hidden" name="status" value={status}/><SubmitButton className={status==='REJECTED'?'button secondary':'button'}>{status==='CONFIRMED'?'Подтвердить':'Ложная тревога'}</SubmitButton></form>)}</div>}
 {candidates.length>0&&<><h3 className="font-bold">Рекомендуемые исполнители</h3><p className="subtle">{i.severity==='CRITICAL'?'Критическая задача будет поставлена перед обычными ожидающими. Работа на месте не прерывается.':'Новое задание будет добавлено в конец плана.'}</p>{candidates.map((c,n)=><form action={assignWorkerAction} key={c.worker.id} className="recommendation"><input type="hidden" name="id" value={id}/><input type="hidden" name="workerId" value={c.worker.id}/><strong className="flex items-center gap-1">{n===0&&<Star size={14} className="text-amber-500" fill="currentColor" aria-label="Лучший вариант"/>}{c.worker.name}</strong><p className="subtle">{c.reason}</p><p className="subtle">{c.route?(c.route.distanceMeters/1000).toFixed(1)+' км · '+Math.ceil(c.route.durationSeconds/60)+' мин по дороге':(c.distance/1000).toFixed(1)+' км по прямой · дорожный ETA недоступен'}</p><p className="subtle">Активных задач: {c.worker.tasks.length}</p><SubmitButton>Подтвердить назначение</SubmitButton></form>)}</>}
 {['CONFIRMED','REOPENED'].includes(i.status)&&!candidates.length&&<p className="subtle">Нет доступных специалистов на смене. Администратор может обновить смены.</p>}
 {i.status==='RESOLVED'&&<form action={updateIncidentAction} className="grid gap-3"><input type="hidden" name="id" value={id}/><input type="hidden" name="status" value="REOPENED"/><label className="field">Причина возврата<textarea name="comment" required minLength={5} maxLength={1000}/></label><SubmitButton className="button danger">Вернуть на доработку</SubmitButton></form>}</>}
 {u.role==='WORKER'&&i.task&&<><p>{taskLabel[i.task.status]}</p>{nextTask&&<form action={updateTaskAction} className="grid gap-3"><input type="hidden" name="id" value={id}/><input type="hidden" name="status" value={nextTask}/>{nextTask==='COMPLETED'&&<><label className="field">Что выполнено<textarea name="comment" required maxLength={2000}/></label><label className="field">Обязательное фото после<input name="photo" type="file" accept="image/jpeg,image/png,image/webp" required/></label></>}<SubmitButton>{({ACCEPTED:'Принять задачу',ON_THE_WAY:'Выехал',ON_SITE:'На месте',COMPLETED:'Завершить с фото'})[nextTask]}</SubmitButton></form>}<Link href={'/worker/route/'+id} className="button secondary">Маршрут</Link></>}
 {u.role==='ADMIN'&&<p className="subtle">Решения по инцидентам принимают диспетчеры.</p>}</div></section><section className="panel"><MapView className="detail-map" points={[{id,title:i.title,lat:i.lat,lng:i.lng,kind:resident?'resident':'incident',type:i.type,severity:i.severity,subtitle:i.address,href:null}]}/></section></div></div></>;
}

